#!/usr/bin/env bash

if [ ! -f ./src/__main__.py ]; then
    echo $'\e[01;31m-- You need to cd into the repository'\'$'s root directory --\e[00m'
    exit 140
fi

./dev/tests/correct-pony-f
./dev/tests/correct-pony+f
./dev/tests/auto-completion
./dev/tests/auto-completion-tool
