.TH PONYSAY 6 "Maj 30, 2013"
.SH NAME
ponysay \- Cowsay reimplementation för ponnyer
.SH ÖVERSIKT
.B ponysay
.RI [ alternativ ]
[--]
.RI [ meddelande ]
.br
.B ponythink
.RI [ alternativ ]
[--]
.RI [ meddelande ]
.br
.SH BESKRIVNING
.PP
\fBponysay\fP visar en bild av en ponny som säger en text som ges av användaren i en terminal.
Om \fImeddelande\fP inte har angivits, kommer indata från ’standard input’ användas. Meddelandet
kommer automatiskt radbryas vid runt 60 kolonner, och ponnyen med meddelandet kommer att skrivas
ut till ’standard output’.
.PP
Om inga argument används kommer programmet bara acceptera indata från ’standard input’ om det
kommer från att annat program, en fil eller ett här-dokument eller här-sträng (se man bash(1)
för detaljer om här-dokument och här-strängar.)
.PP
\fBponythink\fP är till \fIponysay\fP som \fIcowthink\fP är till \fIcowsay\fP.
.PP
För en omfattande dokumentation kör `info ponysay`.
.SH ALTERNATIV
En sammanfattning av alternative är listad nedan.
.TP
.B \-h, \-\-help
Visa sammanfattning av alternativ.
.TP
.B \-v, \-\-version
Visa programmets version.
.TP
.B \-f, \-\-file, \-\-pony \fInamn\fP
Välj en ponny (antingen ett filnamn eller ponnynamn); du kan använda detta val flera gånger
för att få en av dem slumpmässigt utvalt.
.TP
.B \+f, \+\+file, \+\+pony \fInamn\fP
Välj en ponny som inte är med i My Little Pony: Vänskap är magisk [sic!] (antingen ett filnamn
eller ponnynamn); du kan använda detta val flera gånger för att få en av dem slumpmässigt utvalt.
.TP
.B \-F, \-\-any\-file, \-\-anyfile, \-\-anypony \-\-any\-pony \fIname\fP
Detta alternativ är en kombination av \fI-f\fP och \fI+f\fP.
.TP
.B \-\-f, \-\-files, \-\-ponies \fI[namn...]\fP
Variadisk variant av \fI-f\fP, innebärande att alla argument som följer detta tolkas som
värde för detta.
.TP
.B \+\+f, \+\+files, \+\+ponies \fI[namn...]\fP
Variadisk variant av \fI+f\fP, innebärande att alla argument som följer detta tolkas som
värde för detta.
.TP
.B \-\-F, \-\-any\-files, \-\-anyfiles, \-\-anyponies \-\-any\-ponies \fIname\fP
Detta alternativ är en kombination av \fI--f\fP och \fI++f\fP.
.TP
.B \-q, \-\-quote [\fInamn\fP...]
Genom att använda detta alternativ kommer en ponny att skrivas ut med ett citat från
henne själv i My Little Pony: Vänskap är magisk. Ponnyen kommer att väljas slumpmässigt
om inget värde ges. Om mer än en ponny anges genom \fI-q\fP kommer en av dem väljas ut
slumpmässigt.
.TP
.B \-\-q, \-\-quotes [\fInamn\fP...]
Variadisk variant av \fI-q\fP, innebärande att alla argument som följer detta tolkas som
värde för detta.
.TP
.B \-b, \-\-bubble, \-\-balloon \fIstil\fP
Specifiera en talrutestil som ska användas, detta kan antingen vara ett filnamn eller ett
talrutestilsnamn som listas av \fIponysay -B\fP.
.TP
.B \-W, \-\-wrap \fIkolonn\fP
Skärmkolonnen till vilket meddelandet kommer att begrännas; talrutans kanters bredd kommer
at räknas in. Om värdet inte är ett nummer, men istället börjar med \fIn\fP kommer ingen
begränsning användas, och om det börjar med \fIi\fP kommer terminals bredd att användas.
.TP
.B \-c, \-\-compress, \-\-compact [\fIansi-färg\fP]
Packar ihop meddelande på samma sätt som \fIcowsay\fP kör, det är i princip utan multipla
mellanrum och endast styckeseparation.
.TP
.B \-l, \-\-list
Lista ponnyer.
.TP
.B \-L, \-\-symlist, \-\-altlist
Lista ponnyer med alternativa namn inom parantes.
.TP
.B \+l, \+\+list
Lista icke-MLP:Väm-ponnyer.
.TP
.B \+L, \+\+symlist, \+\+altlist
Lista icke-MLP:Väm-ponnyer med alternativa namn inom parantes.
.TP
.B \-B, \-\-bubblelist, \-\-balloonlist \fIstil\fP
Lista alla talrutestiler.
.TP
.B \-A, \-\-all
Lista alla ponier, både MLP:Väm-ponnyer och icke-MLP:Väm-ponnyer. Först listas
MLP:Väm-ponnyer och sedan icke-MLP:Väm-ponnyer.
.TP
.B \+A, \+\+all, \-\-symall, \-\-altall
Lista alla ponier med alternativa namn inom parantes, både MLP:Väm-ponnyer och
icke-MLP:Väm-ponnyer. Först listas MLP:Väm-ponnyer och sedan icke-MLP:Väm-ponnyer.
.TP
.B \-o, \-\-pony\-only, \-\-ponyonly
Rita bara ut ponnyer, ingenting annat, igen talruta och inget meddelande.
.TP
.B \-i, \-\-info
Genom att ligga till detta alternativ kommer metadata för ponnyen skrivas ut
istället för ponnyen.
.TP
.B \+i, \+\+info
Detta fungerar som \fI-i\fP, förutom att utdatat kommer att användas som ponnyns
meddelande istället för att bara skriva ut metadatat.
.TP
.B \-r, \-\-restriction
Detta alternativ används för att begränsa, baserat på metadata, vilka ponnyer som kan
slumpmässigt väjas ut. Att värde i för detta alternativ är en kombination av ett tag-namn
och ett tag-värde på formen \fINAMN=VÄRDE\fP. (Läs `info ponysay` för mer information.)
.TP
.B \-X, \-\-256\-colours, \-\-256colours, \-\-x\-colours
Använd \fIxterm\fP’s 256\-färgstöd (stöds av de flesta X11 terminalerna), oavsätt din
terminals egentliga kompatibiliteter.
.TP
.B \-V, \-\-tty\-colours, \-\-ttycolours, \-\-vt\-colours
Använd Linux VT:s kompatibiliteter \fPutan\fP att utnyttja KMS oavsätt din terminals
egentliga kompatibiliteter.
.TP
.B \-K, \-\-kms\-colours, \-\-kmscolours
Använd Linux VT:s kompatibiliteter \fPoch\fP utnyttja KMS oavsätt din terminals
egentliga kompatibiliteter. (Fungerar inte på alla KMS videokort.)
.TP
.B \+c, \-\-colour [\fIansi-färg\fP]
Färglägg talrutan, inklusive länken och meddelandet. För mer färgläggningsegenskaper,
se \fIinfo\fP-manualen. Argumentet, \fIansi-färg\fP, ska vara en ANSI-färgsekvens utan
inledande CSI och utan avslutande \fIm\fP, till exempel kommer \fI1;31\fP göra det
röd och tjockt (eller ljust beroende på terminalen.)
.TP
.B \-\-colour\-bubble, \-\-colour\-balloon [\fIansi-färg\fP]
Precis som \fI\--colour\fP, förutom att endast talrutan, och ingendera av meddelandet
och länken, kkommer att färgläggas.
.TP
.B \-\-colour\-link [\fIansi-färg\fP]
Precis som \fI\--colour\fP, förutom att endast länken kommer att färgläggas.
.TP
.B \-\-colour\-msg, \-\-colour\-message [\fIansi-färg\fP]
Precis som \fI\--colour\fP, förutom att endast meddelandet kommer att färgläggas.
.TP
.B \-\-colour\-pony [\fIansi-färg\fP]
Precis som \fI--colour\fP, förutmo att ponnien kommer ett färgläggas. Detta
kommer bara ge effekt om ponnyn inte är en vanlig ponny och saknas sin egna färgläggning.
.TP
.B \-\-colour\-wrap, \-\-colour\-hyphen [\fIansi-färg\fP]
Precis som \fI--colour\fP, förutom att bindestrecken som läggs in vid breddbegränsning
kommer att färgläggas. För samma färg som texten, använd \fI0\fP, standardfärgen är
\fi31\fP (rött).
.SH SYSTEMVARIABLER
.TP
.B PONYSAY_BOTTOM
Under TTY (Linux VT), om utskriften är större än skärmens höjd, endast början kommer att
skrivas ut, och två tomma rader lämnas. Om du vill ha slutet istället för höjden utskriven,
exportera \fIPONYSAY_BOTTOM\fP med värdet \fIyes\fP, \fIy\fP eller \fI1\fP.
.TP
.B PONYSAY_SHELL_LINES
Under TTY (Linux VT), om utskrifteb är större än skärmens höjd, två rader kommer att lämnas
tommer. Om du vill ha fler, eller färre, tomma rader kan du exportera \fIPONYSAY_SHELL_LINES\fP
med värde av hur många tomma rader du vill ha.
.TP
.B PONYSAY_FULL_WIDTH
Om du exporterar \fIPONYSAY_FULL_WIDTH\fP med värdet \fIyes\fP, \fIy\fP eller \fI1\fP kommer
utskriften inte att beskäras på bredde för att få plats i terminalen.
.TP
.B PONYSAY_TRUNCATE_HEIGHT
Exportera \fIPONYSAY_TRUNCATE_HEIGHT\fP med värdet \fIyes\fP, \fIy\fP eller \fI1\fP om du
vill beskära utskriften på höjden även om du inte för \fIponysay\fP under TTY (Linux VT).
.TP
.B PONYSAY_UCS_ME
Exportera \fIPONYSAY_UCS_ME\fP med värdet \fIyes\fP, \fIy\fP eller \fI1\fP, om du vill ha
simulerade symboliska länkar till ponnyer med Universal Character Set in deras namn.
.TP
.B PONYSAY_KMS_PALETTE, PONYSAY_KMS_PALETTE_CMD
\fIPONYSAY_KMS_PALETTE\fP eller \fIPONYSAY_KMS_PALETTE_CMD\fP används för att talla om för
\fIponysay\fP how din TTY-färgpalett ser ut, detta egenskap låter dig få bästa möjliga bild
under TTY om du har Kernel Mode Setting-stöd (KMS).
.TP
.B PONYSAY_TYPO_LIMIT
\fIponysay\fP kan autokorregera felstavade namn på ponnyer och talrutestilar.
Utan hänsyn till transpositionering kommer det viktade avståndet användas för att
avgöra vilket namn som ska väljas, om avståndet är större än 5 kommer ingen korrektion
att ske. Detta begränsing kan andras genom exportera en ny begränsning till \fIPONYSAY_TYPO_LIMIT\fP.
Om gränsen sätts till noll stängs autokorrektion av.
.TP
.B PONYSAY_WRAP_HYPHEN
Du kan exportera till \fIPONYSAY_WRAP_HYPHEN\fP vilket tecken du vill använd stället för
binnesträck när ponysay begrännsar bredden på ett meddelande.
.TP
.B PONYSAY_WRAP_LIMIT
Definierar hur långt ett ord måste vara för att avstavas. Avstavning kan ske även om ordet
inte är tillräckligt långt om det krävs.
.TP
.B PONYSAY_WRAP_EXCEED
Definierar hur mycket av ett som måste gå utan för gränsen för att avstavs. Detta används
tillsammans med \fIPONYSAY_WRAP_LIMIT\fP.
.SH FEL
Fel kan rapporteras på <\fBhttps://github.com/erkin/ponysay/issues\fP>.
.SH SE OCKSÅ
.BR cowsay (0),
.BR fortune (0),
.BR ponysay-tool (0),
.BR `info\ ponysay`.
.br
.SH FÖRFATTARE
ponysay är skriven av Erkin Batu Altunbaş <erkinbatu@gmail.com> med bidrag från Mattias Andrée,
Elis Axelsson, Sven-Hendrik Haase, Pablo Lezaeta, Jan Alexander Steffens et al.
.\" See file CREDITS for full list.
.PP
Denna ’manpage’ skrevs först av Louis Taylor <kragniz@gmail.com> för Debin GNU/Linux-projektet
(och får används av andra), och har redigeras av ponysay's skapare för inkludering i ponysay.
.br
.PP
Detta program är under licensen GNU GPLv3+.
.\" See file COPYING to see the license.
