.TH PONYSAY\-TOOL 0 "April 05, 2013"
.SH NAME
ponysay\-tool \- Tool chest for ponysay
.SH SYNOPSIS
.B ponysay-tool
.RI [ options ]
[--]
.RI [ file if apply ]
.br
.SH DESCRIPTION
.PP
\fBponysay\-tool\fP this is a ponysay developing tool that can edit metadata for
\fB.pony\fP files and others options related to \fBpony file\fP modifications.
If \fIfile\fP is not provided, then fallback to \-\-help.
.PP
.PP
For an extensive documentation run `info ponysay`.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B\-v, \-\-version
Print the version of the program.
For now is same as \fIponysay \-v\fP
.TP
.B \-\-kms
Generate all kmsponies for the current TTY palette, not work in all videos.
.TP
.B \-\-dimensions [\fIPONYDIR\fP]
Generate pony dimension file for a directory, useful at build time.
.TP
.B \-\-metadata [\fIPONYDIR\fP]
Generate pony metadata collection file for a directory, useful at build time.
.TP
.B \-b, \-\-browse [\fIPONYDIR\fP]
Browse ponies in a directory and show them.
This option NEED a \fIPONYDIR\fP for work. 
.TP
.B \-b, \-\-restrict [\fIPONYDIR\fP]
Metadata based restriction for \fI\-\-browse\fP, you can restrict the ponies showed in
\fI\-\-browse\fP using same sintaxis as \fIponysay \-\-restrict\fP.
Due that \-\-browse need a \fIPONYDIR\fP this option need to be last alongside they
restrictions.
.TP
.B \-\-edit [\fIPONYFILE\fP]
Edit a pony file\'s metadata filling a predefined template.
The metadata editor have a \fIEMACS\fP alike syntaxis key combination.
.TP
.B \-\-edit\-rm [\fIPONYFILE\fP]
Remove metadata from a \fIpony file\fP, use with caution because deleted metadata is unrecoverable
unless you reintall the affected \fIpony file\fP directrly from the source code or a backup.
.TP
.B \-\-edit\-apply [\fIPONYFILE\fP]
Apply metadata from stdin to a \fIpony file\fP, this include \fBHEIGHT\fP and \fBWIDTH\fP.
`info ponysay` include a trick that include \-\-edit\-stash that easy the metadata edition
in large amount of \fIpony file\fP
.TP
.B \-\-edit\-stash [\fIPONYFILE\fP]
Print applyable meta with data from a \fIpony file\fP, can by used alongside whit 
`ponysay\-tool \-\-edit\-apply` in a combo for apend metadata in the same pony with a 
different pose but being the same character.
.SH BUG
Bugs can be reported in <\fBhttps://github.com/erkin/ponysay/issues\fP>.
.SH SEE ALSO
.BR ponysay.
.BR `info\ ponysay`
.br
.SH AUTHOR
ponysay was written by Erkin Batu Altunbaş <erkinbatu@gmail.com>
with contributions from Mattias Andrée, Elis Axelsson, Sven-Hendrik Haase,
Pablo Lezaeta, Jan Alexander Steffens et al.
.\" See file CREDITS for full list.
.PP
This manual page was originally written by Pablo Lezaeta <prflr88@gmail.com>
for ponysay release.
.br
.PP
This program is licensed under GNU GPLv3+.
.\" See file COPYING to see the license.
