.TH PONYSAY 6 "Mayıs 28, 2013"
.SH AD
ponysay \- Poniler için cowsay uygulaması
.SH KULLANIM
.B ponysay
.RI [ seçenekler ]
[--]
.RI [ ileti ]
.br
.B ponythink
.RI [ seçenekler ]
[--]
.RI [ ileti ]
.br
.SH TANIM
.PP
\fBponysay\fP kullanıcı tarafından sağlanan bir metni söyleyen bir poni resmini uçbirimde
sergiler. Eğer bir \fIileti\fP sağlanmamışsa, standart girdi alır, yaklaşık altmışıncı sütundan
sonra sözcük kaydırma yaparak verilen iletiyi söyleyen poniyi standart çıktıyla yazdırır.
.PP
Eğer hiçbir seçenek sağlanmamışsa; program yalnızca bir diğer programdan, bir dosyadan veya ya
here belgesinden ya da "here sözcesinden" borulanan standart girdiyi alır. (Here belgesi/sözcesi
üzerine ayrıntılı bilgi için bakınız: man bash(1))
alır.
.PP
\fIponysay\fP için \fBponythink\fP, \fIcowsay\fP için \fIcowthink\fP gibidir.
.PP
Ayrıntılı belgelendirme için `info ponysay`e başvurun.
.SH SEÇENEKLER
Seçeneklerin bir özeti aşağıda verilmiştir.
.TP
.B \-h, \-\-help
Seçeneklerin bir özetini yazdır.
.TP
.B \-v, \-\-version
Programın sürümünü yazdır.
.TP
.B \-f, \-\-file, \-\-pony \fIad\fP
Poni seç (ya bir dosya ya da bir poni adı); bu seçeneği birden çok kez kullanabilirsiniz, içlerinden biri rastgele
seçilecektir.
.TP
.B \+f, \+\+file, \+\+pony \fIad\fP
My Little Pony: Arkadaşlık Sihirlidir'de bulunmayan bir poni seçimi (ya bir dosya ya da bir
poni adı); bu seçeneği birden çok kez kullanabilirsiniz, içlerinden biri rastgele seçilecektir.
.TP
.B \-F, \-\-any\-file, \-\-anyfile, \-\-anypony \-\-any\-pony \fIad\fP
Bu seçenek \fI-f\fP ile \fI+f\fP'yi birleştirir.
.TP
.B \-\-F, \-\-any\-files, \-\-anyfiles, \-\-anyponies \-\-any\-ponies \fIad\fP
Bu seçenek \fI--f\fP ile \fI++f\fP'yi birleştirir.
.TP
.B \-\-f, \-\-files, \-\-ponies [\fIad...\fP]
\fI-f\fP'nin değişkin türevi; yani bu seçeneğin ardından eklenen tüm değişkenler bu seçeneğin
değişkeni olarak yorumlanacaktır.
.TP
.B \+\+f, \+\+files, \+\+ponies [\fIad...\fP]
\fI+f\fP'nin değişkin türevi.
.TP
.B \-q, \-\-quote [\fIekle\fP...]
Bu seçeneğin kullanılmasıyla bir poni, My Little Pony: Arkadaşlık Sihirlidir'deki
replikleriyle yazdırılacaktır. En az bir poni \fI-q\fP'ye bir değişken verilmediği sürece
poni rastgele seçilecektir. Eğer birden çok poni değişkeni sağlanırsa; poni, değişkenler
arasından rastgele seçilecektir.
.TP
.B \-\-q, \-\-quotes [\fIad\fP...]
\fI-q\fP'nun değişkin türevi. Ayrıca bu değişkenler \fI-q\fP'ye de eklenir.
.TP
.B \-b, \-\-bubble, \-\-balloon \fIbiçim\fP
Kullanılacak balon biçimini belirt; bu ya bir dosya adı ya da \fIponysay -B\fP
ile yazdırılmış bir balon adı olabilir.
.TP
.B \-W, \-\-wrap \fIsütun\fP
İletinin kaydırılacağı ekran sütunu, balonun ek genişliği göz önünde tutulur. Eğer değişken
bir sayı değil ise; eğer \fIn\fP ile başlıyorsa sözcük kaydırma yapılmaz, \fIi\fP ile
başlıyorsa uçbirimin genişliği kullanılır.
.TP
.B \-c, \-\-compress, \-\-compact [\fIANSI-rengi\fP]
İletiyi \fIcowsay\fP'in yaptığı gibi sıkıştır, yani çoklu boşluklar olmadan ve yalnız satırbaşı
aralıklarıyla.
.TP
.B \-l, \-\-list
Poni dosyalarını sırala.
.TP
.B \-L, \-\-symlist, \-\-altlist
Poni dosyalarını köşeli ayraç içinde almaşık adlarıyla sırala.
.TP
.B \+l, \+\+list
My Little Pony: Arkadaşlık Sihirlidir dışındaki poni dosyalarını sırala.
.TP
.B \+L, \+\+symlist, \+\+altlist
My Little Pony: Arkadaşlık Sihirlidir dışındaki poni dosyalarını köşeli ayraç içinde almaşık
adlarıyla sırala.
.TP
.B \-B, \-\-bubblelist, \-\-balloonlist \fIstyle\fP
Tüm balon biçimlerin sırala.
.TP
.B \-A, \-\-all
Tüm poni dosyalarını sırala, My Little Pony: Arkadaşlık Sihirlidir içinde ve dışındakilerin
tümünü. Bu durumda içindekiler önce, dışındakiler sonra yazdırılır.
.TP
.B \+A, \+\+all, \-\-symall, \-\-altall
Tüm poni dosyalarını ayraç içinde almaşık adlarıyla sırala.
.TP
.B \-o, \-\-pony\-only, \-\-ponyonly
Yalnız poniyi yazdır, konuşma balonunu yoksay.
.TP
.B \-i, \-\-info
Poninin metaverisini yazdır, kendisini değil.
.TP
.B \+i, \+\+info
Poniye metaverisini söylet.
.TP
.B \-r, \-\-restriction
Bu seçenek, rastgele seçilecek olan ponileri metaverilerine göre sınırlandırır. Geçerli bir
değişken \fIAD=DEĞER\fP biçiminde bir etiket adı ve etiket değeri birleşimindedir.
.TP
.B \-X, \-\-256\-colours, \-\-256colours, \-\-x\-colours
Uçbirimin gerçek özelliklerini yoksayarak \fIxterm\fP'in (çoğu X11 uçbirimlerince desteklenen)
256\-renk desteğini kullan.
.TP
.B \-V, \-\-tty\-colours, \-\-ttycolours, \-\-vt\-colours
Uçbirimin gerçek özelliklerini yoksayarak (KMSsiz) Linux VT'nin özelliklerini
kullan.
.TP
.B \-K, \-\-kms\-colours, \-\-kmscolours
Uçbirimin gerçek özelliklerini yoksayarak (KMS ile) Linux VT'nin özelliklerini kullan.
(Tüm KMS ekran kartlarıyla çalışmayabilir.)
.TP
.B \+c, \-\-colour [\fIANSI-rengi\fP]
Balonu, bağlantıyı ve iletiyi boya. Daha çok boyama özelliği için bakınız: `info ponysay`
Değişken \fIANSI-rengi\fP, önünde bir CSI ve ardında \fIm\fP bulunmayan bir ANSI rengi olmalıdır.
Örneğin; \fI1;31\fP, metnin kırmızı ve kalın (veya parlak, uçbirime göre değişir) olmasını sağlar.
.TP
.B \-\-colour\-bubble, \-\-colour\-balloon [\fIANSI-rengi\fP]
\fI\-\-colour\fP gibi, ancak yalnız balonu boya.
.TP
.B \-\-colour\-link [\fIANSI-rengi\fP]
\fI\-\-colour\fP gibi, ancak yalnız balon bağlantısını boya.
.TP
.B \-\-colour\-msg, \-\-colour\-message [\fIANSI-rengi\fP]
\fI\-\-colour\fP gibi, ancak yalnız iletiyi boya.
.TP
.B \-\-colour\-pony [\fIANSI-rengi\fP]
\fI\-\-colour\fP gibi, ancak poniyi boya.
Bu boyamanın gerçek poni dosyaları üzerinde bir etkisi yoktur.
.TP
.B \-\-colour\-wrap, \-\-colour\-hyphen [\fIANSI-rengi\fP]
\fI\-\-colour\fP gibi, ancak sözcük kaydırmayla eklenen tireyi boyar.
Renksiz için \fI0\fP'ı kullanın, öntanımlı değer \fi31\fP'dir.
.SH ÇEVRE
.TP
.B PONYSAY_BOTTOM
TTY (Linux VT) içerisinde eğer çıktı ekran yüksekliğinden büyükse, yalnızca başı
yazdırılarak iki dize boş bırakılır. Eğer başı yerine sonunun yazdırılmasını istiyorsanız,
\fIPONYSAY_BOTTOM\fP'yi \fIyes\fP, \fIy\fP veya \fI1\fP değerlerinden biriyle ihraç edin.
.TP
.B PONYSAY_SHELL_LINES
TTY (Linux VT) içerisinde eğer çıktı ekran yüksekliğinden büyükse, yalnızca başı
yazdırılarak iki dize boş bırakılır. Eğer daha çok veya az boş dizenin kullanılmasını
istiyorsanız, \fIPONYSAY_SHELL_LINES\fP'ı dilediğiniz dize sayısının değeriyle ihraç edin.
.TP
.B PONYSAY_FULL_WIDTH
Çıktının uçbirime sığdırılması için sıkıştırılmasını istemiyorsanız \fIPONYSAY_FULL_WIDTH\fP'i
\fIyes\fP, \fIy\fP veya \fI1\fP değerlerinden biriyle ihraç edin.
.TP
.B PONYSAY_TRUNCATE_HEIGHT
Eğer TTY içerisinde olmasanız bile çıktının sıkıştırılmasını istiyorsanız,
\fIPONYSAY_TRUNCATE_HEIGHT\fP'i \fIyes\fP, \fIy\fP veya \fI1\fP değerlerinden biriyle ihraç
edin.
.TP
.B PONYSAY_UCS_ME
Eğer Evrensel Karakter Seti kullanan poni dosyalarına [öykünülmüş] simgesel bağlantı
istiyorsanız, \fIPONYSAY_UCS_ME\fP'yi \fIyes\fP, \fIy\fP veya \fI1\fP değerlerinden biriyle
ihraç edin.
.TP
.B PONYSAY_KMS_PALETTE, PONYSAY_KMS_PALETTE_CMD
\fIPONYSAY_KMS_PALETTE\fP veya \fIPONYSAY_KMS_PALETTE_CMD\fP değerleri ponysay'e TTY
renklerinizin nasıl göründüğünü bildirmekte kullanılır. Bu özellik, KMS desteği varsa
TTY'nizde en iyi nitelikte görüntü elde etmenizi sağlar.
.TP
.B PONYSAY_TYPO_LIMIT
\fIponysay\fP yanlış yazılan poni ve balon biçim adlarını düzeltebilir. Aktarmayı göz
önünde bulundurmadan, öntanımlı olarak eğer ağırlıklı uzaklık en yakın sözcükler için
beşten çoksa düzeltme yoksayılır. Bu sınırı \fIPONYSAY_TYPO_LIMIT\fP'i dilediğiniz sayısal
değerle ihraç ederek değiştirebilirsiniz. Sınırı sıfır kılmak düzeltmeyi devredışı bırakır.
.TP
.B PONYSAY_WRAP_HYPHEN
Sözcük kaydırma sırasında \fIponysay\fP'in tire (\-) yerine hangi imi kullanması
gerektiğini \fIPONYSAY_WRAP_HYPHEN\fP'ı bir sözce değeriyle ihraç ederek belirtebilirsiniz.
.TP
.B PONYSAY_WRAP_LIMIT
Bir sözcüğün tireyle ayrılması için ne denli uzun olması gerektiğini tanımlar.
Bu değer, çıktıyı süslemek amacıyla uzun sözcükleri kaydırmak için kullanılır. Bu, bir
sözcüğün tireyle ayrıldığı tek koşul değildir; eğer sözcük başka türlü sığmıyorsa
da tireyle ayrılabilir.
.TP
.B PONYSAY_WRAP_EXCEED
Bir sözcüğün tireyle ayrılması için kaydırılma noktasını ne denli aşması gerektiğini
tanımlar. Bu değer \fIPONYSAY_WRAP_LIMIT\fP ile birlikte kullanılır.
This setting is used togather with \fIPONYSAY_WRAP_LIMIT\fP.
.SH HATA
Hatalar <\fBhttps://github.com/erkin/ponysay/issues\fP> adresinde bildirilebilir.
.SH AYRICA BAKINIZ
.BR cowsay(0),
.BR fortune(0),
.BR ponysay-tool (0),
.BR `info\ ponysay`.
.br
.SH AUTHOR
ponysay, Erkin Batu Altunbaş <erkinbatu@gmail.com> tarafından
Mattias Andrée, Elis Axelsson, Sven-Hendrik Haase, Pablo Lezaeta, Jan Alexander Steffens
ve diğerlerinin katkılarıyla yazılmıştır. Tam sıralama için CREDITS dosyasına bakınız.
.PP
Bu kılavuz sayfası aslen Louis Taylor <kragniz@gmail.com> tarafından Debian GNU/Linux
projesi için (başkalarınca da kullanılabilecek biçimde) yazılmış olup, resmî ponysay
dağıtımı için ponysay yazarlarınca düzenlenmiştir.
.br
Türkçe çeviri Erkin Batu Altunbaş tarafından yapılmıştır.
.br
.PP
Bu program GNU Genel Kamu Lisansı altında olup lisansta belirtilen koşullar uyarınca
dağıtımı, değiştirilmesi ve satışına izin verilmektedir. Tüm lisans metnini görmek için
LICENCE adlı dosyaya bakınız.
