.TH PONYSAY 6 «09 de noviembre del 2013»
.SH NOMBRE
ponysay \- Una reimplementación de cowsay usando ponis
.SH SINOPSIS
.B ponysay
.RI [ opciones ]
[--]
.RI [ mensaje ]
.br
.B ponythink
.RI [ opciones ]
[--]
.RI [ mensaje ]
.br
.SH DESCRIPCIÓN
.PP
\fBponysay\fP muestra la imagen de un poni con un texto dado por el usuario,
esto dentro de la terminal.
.br
Si no se da un \fImensaje\fP ponysay aceptará una orden estándar en su lugar.
El mensaje deberá de tener alrededor de 60 columnas, y el o la poni debera de
mostrar este mensaje en una salida estándar.
.PP
Si no se da ningún argumento, el programa solamente aceptará mensajes
estándares provistos por otros programas, un archivo, ambos o una cadena de
caracteres (véase también bash(1) para detalles de archivos y cadenas de caracteres.)
.PP
\fBponythink\fP es a \fIponysay\fP lo que \fIcowthink\fP es a \fIcowsay\fP.
.SH OPCIONES
El resumen de las opciones está incluido a continuación.
.TP
.B \-h, \-\-help
Muestra la ayuda, un resumen de las opciones.
.TP
.B \-v, \-\-version
Muestra la versión del programa.
.TP
.B \-f, \-\-file, \-\-pony \fInombre\fP
Selecciona un poni específico (ya sea un archivo o el nombre directamente),
puede usar esta opción con múltiples ponis y de estos será elegido uno al azar.
.TP
.B \+f, \+\+file, \+\+pony \fInombre\fP
Selecciona un poni no pertenecientes a MLP:FiM (ya sea un archivo o el nombre
directamente), puede usar esta opción con múltiples ponis y de estos será
elegido uno aleatoriamente.
.TP
.B \-F, \-\-any\-file, \-\-anyfile, \-\-anypony \-\-any\-pony \fInombre\fP
Esta opción combina \fI-f\fP y \fI+f\fP.
.TP
.B \-q, \-\-quote [\fInombre\fP...]
Usando esta opción un poni será mostrado dando una cita en inglés de
«My Little Pony: Frienship is magic» (My Little Pony: La magia de la amistad).
Este poni será seleccionado aleatoriamente salvo que uno o varios ponis sean
agregados tras la opción \fI-q\fP, en cuyo caso será seleccionado uno al azar 
de este conjunto.
.TP
.B \-\-f, \-\-files, \-\-ponies \fI[nombre...]\fP
Variable variádica de \fI-f\fP, o sea, todos los argumentos dados después de
este serán pasados a dicha opción.
.TP
.B \+\+f, \+\+files, \+\+ponies \fI[nombre...]\fP
Variable variádica de \fI+f\fP, o sea, todos los argumentos dados después de
este argumento serán pasados a dicha opción.
.TP
.B \-\-F, \-\-any\-files, \-\-anyfiles, \-\-anyponies \-\-any\-ponies \fInombre\fP
Esta opción combina \fI--f\fP y \fI++f\fP.
.TP
.B \-\-q, \-\-quotes [\fInombre\fP...]
Variable variádica de \fI-q\fP, todos los argumentos dados después de este
argumento serán pasados a dicha opción.
.TP
.B \-b, \-\-bubble, \-\-balloon \fIestilo\fP
Especifica el tipo de globo de texto a utilizar, puede ser la ruta a un archivo 
o bien una de las opciones dadas por \fIponysay -B\fP.
.TP
.B \-W, \-\-wrap \fIcolumna\fP
Las columnas de la pantalla en las que debe presentarse el mensaje, la anchura
extra del globo se toma también en consideración. Si el argumento no es un número, 
sino que inicia en su lugar con \fIn\fP, no hay ajuste alguno y si comienza
con \fIi\fP el ancho de la terminal es tomado.
.TP
.B \-c, \-\-compress, \-\-compact [\fIcolor-ANSI\fP]
Comprime en mensaje en la misma manera que \fIcowsay\fP lo hace,
esto es básicamente sin múltiples espacios y solo separando párrafos.
.TP
.B \-l, \-\-list
Lista los y las ponis disponibles.
.TP
.B \-L, \-\-symlist, \-\-altlist
Lista los y las ponis con nombres alternativos (enlaces simbólicos) dentro 
de paréntesis.
.TP
.B \+l, \+\+list
Lista los ponis no pertenecientes a MLP:FiM disponibles.
.TP
.B \+L, \+\+symlist, \+\+altlist
Lista los ponis no pertenecientes a MLP:FiM con nombres alternativos dentro 
de paréntesis.
.TP
.B \-B, \-\-bubblelist, \-\-balloonlist \fIestilo\fP
Muestra la lista de globos de texto disponibles.
.TP
.B \-A. \-\-all
Lista todos y todas las ponis, tanto pertenecientes a MLP:FiM como no, en la 
primera lista se mostrarán los pertenecientes y la subsiguiente los que no.
.TP
.B \+A, \+\+all, \-\-symall, \-\-altall
Lista todos los ponis incluyendo sus nombres alternativos, estos pertenecientes 
a MLP:FiM cono no, en la primera lista se mostrarán los pertenecientes y la
subsiguiente los no.
.TP
.B \-o, \-\-pony\-only, \-\-ponyonly
Solamente muestra a la o el poni, pero no los demás elementos.
.TP
.B \-i, \-\-info
Agregando esta opción podrá ver los metadatos del poni en lugar de este.
.TP
.B \+i, \+\+info
Esta opción funciona como \fI-i\fP, solamente que el poni mostrará la 
información en un globo de texto.
.TP
.B \-r, \-\-restriction
Esta opción limita cuales ponis serán mostrados basados en sus metadatos.
Un valor para este argumento es una combinación del nombre de la etiqueta en 
la forma de \fINOMBRE=VALOR\fP.
.TP
.B \-X, \-\-256\-colours, \-\-256colours, \-\-x\-colours
Usa el soporte de 256 colores de \fIxterm\fP (soportado por la mayoría de
terminales en X11), sin diferencia entre las capacidades de la terminal.
.TP
.B \-V, \-\-tty\-colours, \-\-ttycolours, \-\-vt\-colours
Usa el soporte de colores de la terminal VT de Linux \fPsin\fP usar KMS, indiferente
de las capacidades de la terminal.
.TP
.TP
.B \-K, \-\-kms\-colours, \-\-kmscolours
Usa el soporte de colores de la terminal VT de Linux \fPusando\fP KMS, indiferente 
de las capacidades de la terminal (no funciona en todas las tarjetas con soporte KMS).
.TP
.B \+c, \-\-colour [\fIcolor-ANSI\fP]
Colorea el globo, Incluyendo mensajes y enlaces.
Para más información acerca del coloreo vea las páginas \fIinfo\fP.
El argumento o \fIcolor-ANSI\fP, Puede ser una secuencia de colores ANSI 
sin preceder de CSI y sin la cola \fIm\fP, por ejemplo: \fI1;31\fP puede 
referirse al color rojo y en negrita (o color claro dependiendo de la terminal.)
.TP
.B \-\-colour\-bubble, \-\-colour\-balloon [\fIcolor-ANSI\fP]
Trabaja como \fI\--colour\fP pero solamente colorea el globo de texto.
.TP
.B \-\-colour\-link [\fIcolor-ANSI\fP]
Trabaja como \fI--colour\fP pero solamente colorea en enlace al globo de texto.
.TP
.B \-\-colour\-msg, \-\-colour\-message [\fIcolor-ANSI\fP]
Trabaja como \fI--colour\fP pero solamente colorea el texto.
.TP
.B \-\-colour\-pony [\fIcolor-ANSI\fP]
Trabaja como \fI--colour\fP pero solamente colorea la poni.
Este coloreo no tiene efecto en archivos poni dado que tienen su propio coloreo.
.TP
.B \-\-colour\-wrap, \-\-colour\-hyphen [\fIcolor-ANSI\fP]
Trabaja como \fI--colour\fP pero solo colorea guiones agregados por la 
envoltura del texto.
Si desea remover el color use \fI0\fP (cero), 
por omisión es \fI31\fP (treintaiuno).
.SH VARIABLES DE ENTORNO
.TP
.B PONYSAY_BOTTOM
Bajo TTY (Linux VT), si la imagen es más larga que la anchura de la terminal 
en pantalla, solamente el inicio de esta es impreso, dejando únicamente dos
líneas blancas, pero si desea que a pesar de todo sea impreso el fondo puede
exportar \fIPONYSAY_BOTTOM\fP con el valor \fIyes\fP, \fIy\fP o \fI1\fP.
.TP
.B PONYSAY_SHELL_LINES
Bajo TTY (Linux VT), si la imagen es más larga que la anchura de la terminal
en pantalla, solamente dos líneas blancas serán impresas.
Si desea más o menos líneas blancas, puede exportar \fIPONYSAY_SHELL_LINES\fP
con el valor de cuantas desea.
.TP
.B PONYSAY_FULL_WIDTH
Puede exportar \fIPONYSAY_FULL_WIDTH\fP con el valor \fIyes\fP, \fIy\fP o 
\fI1\fP, si desea que la salida sea truncada para que calce en la terminal.
.TP
.B PONYSAY_TRUNCATE_HEIGHT
Exporte \fIPONYSAY_TRUNCATE_HEIGHT\fP con el valor \fIyes\fP, \fIy\fP o 
\fI1\fP, si desea truncar la salida en el largo aun si no se está dentro de 
una terminal \fIponysay\fP bajo TTY.
.TP
.B PONYSAY_UCS_ME
Exporte \fIPONYSAY_UCS_ME\fP con el valor \fIyes\fP, \fIy\fP o \fI1\fP, si es 
que busca «simular enlaces simbólicos» a ponis usando 
«Universal Character Set» (Conjunto de Caracteres Universal) [UCS] apuntando a 
sus nombres.
.TP
.B PONYSAY_KMS_PALETTE, PONYSAY_KMS_PALETTE_CMD
\fIPONYSAY_KMS_PALETTE\fP o \fIPONYSAY_KMS_PALETTE_CMD\fP es usado para llamar a
ponysay usando la paleta TTY tal cual es, esto es usado para mostrar a las ponis
usando la mejor calidad de colores posible si esta bajo TTY y si su vídeo 
soporta «Kernel Mode Seting» (KMS) y este está activo.
.TP
.B PONYSAY_TYPO_LIMIT
\fIponysay\fP es capaz de autocorregir nombres mal escritos y tipos de globo de 
texto sin considerar la trasposición de texto, por omisión si la distancia 
ponderada es mayor a 5 (cinco) para la palabra más cercana, entonces es 
ignorada la autocorrección.
Este limite puede ser cambiado si se exporta un numero a la variable 
\fIPONYSAY_TYPO_LIMIT\fI; Dejando este valor en 0 se desactiva la 
autocorrección.
.TP
.B PONYSAY_WRAP_HYPHEN
Puede exportar lo que usará ponysay en lugar del guion cuando se envuelven 
los mensajes.
.TP
.B PONYSAY_WRAP_LIMIT
Define cuan larga deberá ser la palabra para que se utilice el guion.
Esta se utilizará para envolver palabras que son muy largas para que así 
la salida sea lo mejor posible.
Esta no es la única condición bajo la cual puede ser cortada una palabra, 
también podrá cortarse si la palabra no puede encajar de otra manera.
.TP
.B PONYSAY_WRAP_EXCEED
Define cuan larga puede llegar a ser una palabra antes de que sea cortada con 
un guion.
Esta opción es usada en conjunto con \fIPONYSAY_WRAP_LIMIT\fP.
.SH FALLOS
.nf
Los fallos pueden ser reportados en
.br
<\fBhttps://github.com/erkin/ponysay/issues\fP>.
.SH VÉASE TAMBIÉN
.BR cowsay (0),
.BR fortune (0),
.BR ponysay-tool (0),
.BR `info\ ponysay`.
.br
.SH AUTOR
ponysay fue escrito por Erkin Batu Altunbaş <erkinbatu@gmail.com>
con la ayuda de Mattias Andrée, Elis Axelsson, Sven-Hendrik Haase,
Pablo Lezaeta, Jan Alexander Steffens y otros.
.\" véase también el archivo CREDITS para la lista completa.
.PP
Este manual originalmente fue escrito por Louis Taylor <kragniz@gmail.com>
para el proyecto Debian GNU/Linux (y puede ser usado por otros), y editado por
los autores de ponysay para el lanzamiento oficial de este.
.br
La actual traducción al español fue escrita por Pablo Lezaeta <prflr88@gmail.com>.
.br
.PP
Este programa está licenciado bajo la «Licencia Pública General de GNU versión 3 o superior» GNU GPLv3+
.\" Véase también el archivo COPYING para ver la licencia completa.
