.\"                                      
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PONYSAY 6 "Julio 13, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOMBRE
ponysay \- un contenedor para cowsay usando ponis
.SH SINOPSIS
.B ponysay
.RI [ opciones ]
.RI [ mensaje ]
.br
.B ponythink
.RI [ opciones ]
.RI [ mensaje ]
.br
.SH DESCRIPCIÓN
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBponysay\fP muestra la imagen de un poni con un texto dado por el usuario, esto dentro de la terminal.
.br
Este es en realidad un contenedor para \fIcowsay\fP, por tanto sigue usando este último para motrar el mensaje.
.br
Si el \fImesaje\fP no es provisto, ponysay aceptará una orden estándar.
El mensaje debería de tener alrededor de 40 columnas, y el o la poni devería de mostrar este mensaje
en una salida estándar.
.PP
Si no se da ningún argumento, el programa solo aceptará mensajes estándares provistos por otros programas,
un archivo, ambos o cadena de caracteres (vease man bash(1) para detalles de archivos y cadenas de caracteres.).
.PP
\fBponythink\fP es a \fIponysay\fP como \fIcowthink\fP es a \fIcowsay\fP.
.SH OPCIONES
El resumen de las opciones está incluido acontinuación.
.TP
.B \-h
Muestra la ayuda, un resumen de las opciones.
.TP
.B \-v
Muestra la versión del programa.
.TP
.B \-l
Lista los ponis disponibles.
.TP
.B \-L
Lista los ponis con nombres sinónimos dentro de corchetes.
.TP
.B \-f \fInombre\fP
selecciona un poni específico (ya sea un archivo o el nombre directamente), puedes usar esta opción con múltiples ponis y de estos será elejído uno al azar.
.TP
.B \-q [\fInombre\fP]...
Usando esta opción un poni será mostrado dando una cita de My Little Pony: Frienship is magic
(My Little Pony: La magia de la amistad). Este poni será seleccionado aleatoriamente salvo que
uno o varios ponis sean agregados tras la opción \fI-q\fP, en cuyo caso se seleccionará aleatoriamente uno 
de este conjunto.
.TP
.B \-W \fIcolumna\fP
El numero de columnas en el que será impreso el mensaje.
.SH ENTORNO
.TP
.B PONYSAY_BOTTOM
Bajo TTY (Linux VT), si la imagen es mas larga que la anchura de la terminal en pantalla, solo el inicio de esta
es impreso, dejando solo dos líneas blancas. si desea que apesar de todo sea impreso el fondo del
inicio puede exportar \fIPONYSAY_BOTTOM\fP con el valor \fIyes\fP, \fIy\fP o \fI1\fP.
.TP
.B PONYSAY_SHELL_LINES
Bajo TTY (Linux VT), si la imagen es mas larga que la anchura de la terminal en pantalla, solo dos líneas blancas
serán impresas. si desea más o menos lineas blancas, puede exportar \fIPONYSAY_SHELL_LINES\fP con
el valor de cuantas líneas blancas desea. Naturalmente esto solo tomará efecto si la salida no es mas
larga que la pantalla.
.TP
.B PONYSAY_FULL_WIDTH
Puede exportar \fIPONYSAY_FULL_WIDTH\fP con el valor \fIyes\fP, \fIy\fP o \fI1\fP, si usted
no desea que la salida sea truncada para que calce en la terminal.
.TP
.B PONYSAY_TRUNCATE_HEIGHT
Exporte \fIPONYSAY_TRUNCATE_HEIGHT\fP con el valor \fIyes\fP, \fIy\fP o \fI1\fP, si
desea truncar la salida en el largo aun si no se está dentro de una terminal \fIponysay\fP bajo TTY.
.SH BUGs
.nf
Los bugs pueden ser reportados en
.br
<\fBhttps://github.com/erkin/ponysay/issues\fP>.
.SH VEA TAMBIÉN
.BR cowsay (1),
.BR fortune (6).
.br
.SH AUTOR
ponysay fue escrito por Erkin Batu Altunbaş <erkinbatu@gmail.com>
con la ayuda de Mattias Andrée, Sven-Hendrik Haase, Jan Alexander Steffens y otros.
.\" vea el archivo CREDITS para la lista completa.
.PP
Este manual originalmente fue escrito por Louis Taylor <kragniz@gmail.com>
para el proyecto Debian GNU/Linux (y puede ser usado por otros), y editado por
Mattias Andrée <maandree@kth.se> para el lanzamiento oficial de ponysay
y traducido por Pablo Lezaeta al español.
.br
La actual traducción al español fue escrita por Pablo Lezaeta <prflr88@gmail.com>.
.br
.PP
Este programa está licenciado bajo la WTFPL
.\" Vea el archivo COPYING para ver la licencia completa.
