.TH PONYSAY\-TOOL 0 «24 de junio del 2014»
.SH NAME
ponysay\-tool \- Aplicación de metadatos para ponysay
.SH SINOPSIS
.B ponysay-tool
.RI [ opciones ]
[--]
.RI [ archivo si lo requiere ]
.br
.SH DESCRIPCIÓN
.PP
\fBponysay\-tool\fP es una aplicación de edición de metadatos para archivos
\fB.pony\fP y opciones relacionadas con la edición de \fBmetadatos de un poni\fP.
Si no se da un \fIarchivo\fP entonces se tratará como si se invocase
\-\-help en su lugar.
.PP
.PP
Para una extensiva documentación ejecute `info ponysay`.
.SH OPCIONES
Acontinuación una breve descripción de las opciones.
.TP
.B \-h, \-\-help
Muestra la ayuda, un resumen de las opciones.
.TP
.B\-v, \-\-version
Muestra la versón y sale.
Por ahora es lo mismo que utilizar \fIponysay \-v\fP
.TP
.B \-\-kms
Genera los kmsponies para la actual paleta en TTY, no funciona en todas las tarjetas.
.TP
.B \-\-dimensions [\fIPONIDIRECTORIO\fP]
Genera las un archivo con la colleción de dimenciones de los ponis en el directotio,
útil en tiempo de compilación.
.TP
.B \-\-metadata [\fIPONIDIRECTORIO\fP]
Genera un archivo con la colección de metadatos de los ponies en el directorio,
útil en tiempo de compilación.
.TP
.B \-b, \-\-browse [\fIPONIDIRECTORIO\fP]
Navega a travez de los ponis en el directorio y los muestra a su vez.
Esta opción NECESITA un \fIDIRECTORIO\fP con ponis para funcionar.
.TP
.B \-b, \-\-restrict [\fIPONIDIRECTORIO\fP]
Limitador de metadatos para \fI\-\-browse\fP, Puede restringir a los ponis mostrados
por \FI\-\-browse\fP usando la misma sintaxis que \fIponysay \-\-restrict\fP.
Debido a eso \-\-browse necesita tener un \fIDIRECTORIO\fP como argumento final además
para funcionar este requiere que los ponis tengan metadatos válidos.
.TP
.B \-\-edit [\fIPONIARCHIVO\fP]
Edita los metadatos de un archivo pony predefinidos por una plantilla, 
El editor utiliza una combinación de teclas como la de \fIEMACS\fP.
.TP
.B \-\-edit\-rm [\fIPONIARCHIVO\fP]
Remueve metadatos desde \fIarchivos ponis\fP, usese con precaución debido a que los metadatos borrados
son irrecuerables, a no ser que los reinstale los \fIarchivos ponis\fP desde un respaldo o desde el
código fuente.
.TP
.B \-\-edit\-apply [\fIPONIARCHIVO\fP]
Agrega metadatos desde «stdin» a un \fIarchivo poni\fI, esto incluye \fBALTURA\P y \fBANCHURA\fP
(\fBHEIGHT\fP y \fBWIDTH respectivamente).
Dentro de `info ponysay` se menciona un truco que implica usar \-\-edit\-stash en una determinada
combinación de órdenes para facilitar la edición de grandes cantidades de \fIarchivos ponis\fP. 
.TP
.B \-\-edit\-stash [\fIPONIARCHIVO\fP]
Imprime los datos junto a su información directamente desde el \fIarchivo poni\fP.
Puede ser usada junto a «ponysay\-tool \-\-edit\-apply» para acelerar la edición de 
\fParchivos ponis\fP con diferente pose siendo el mismo personaje.
.SH FALLOS
Los fallos pueden ser reportados en
<\fBhttps://github.com/erkin/ponysay/issues\fP>.
.SH VÉASE TAMBIÉN
.BR ponysay (6).
.BR `info\ ponysay`
.br
.SH AUTOR
ponysay fue escrito por Erkin Batu Altunbaş <erkinbatu@gmail.com> con la ayuda de
Mattias Andrée, Elis Axelsson, Sven-Hendrik Haase, Pablo Lezaeta, Jan Alexander Steffens y otros.
.\" véase también el archivo CREDITS para la lista completa.
.PP
Este manual originalmente fue escrito por Pablo Lezaeta <prflr88@gmail.com>
para el lanzamiento oficial de ponysay.
.br
La actual traducción al español fue escrita por Pablo Lezaeta <prflr88@gmail.com>.
.br
.PP
Este programa está licenciado bajo la «Licencia Pública General de GNU versión 3 o superior» GNU GPLv3+
.\" Véase también el archivo COPYING para ver la licencia completa.
