#!bash
#
# this is bash completion function file for ponysay.py.
# generated by genzshcomp(ver: 0.5.1)
#

_ponysay.py()
{
  local cur
  local cmd

  cur=${COMP_WORDS[$COMP_CWORD]}
  cmd=( ${COMP_WORDS[@]} )

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $( compgen -W "-h --help --pony -p --quote -q --center -c --center-text -C --width -w --balloon -b" -- $cur ) )
    return 0
  fi
}

complete -F _ponysay.py -o default ponysay.py
