#compdef ponysay ponythink
#
# this is zsh completion function file.
# generated by genzshcomp(ver: 0.5.1)
#

typeset -A opt_args
local context state line

local -a _available_ponies
(( $+functions[_ponysay_pony] )) || _ponysay_pony()
{
  (( $#_available_ponies )) || _available_ponies=($(ponysay -p list) )
  compadd "$@" -a _available_ponies
}

local -a _ponysay_balloons _ponythink_balloons
(( $+functions[_ponysay_pony] )) || _ponysay_balloons(){
  (( $#_ponysay_balloons )) || _ponysay_balloons=($(ponysay -b list))
  (( $#_ponythink_balloons )) || _ponythink_balloons=($(ponythink -b list))
  [[ "$words" == ponythink* ]] && compadd "$@" -a _ponythink_balloons || compadd "$@" -a _ponysay_balloons
}

_arguments -s -w -S \
  "(-h --help)"{-h,--help}"[show this help message and exit]" \
  "(-p= --pony=)"{-p,--pony}"[The name of the pony to be used. Use \"-p list\" to list all ponies, \"-p random\" (default) to use a random pony.]:PONY:_ponysay_pony" \
  "(-q --quote)"{-q,--quote}"[Use a random quote of the pony being displayed as text]" \
  "(-c --center)"{-c,--center}"[Center the pony]" \
  "(-C --center-text)"{-C,--center-text}"[Center the text in the bubble]" \
  "(-w= --width=)"{-w,--width}"[Terminal width. Use 0 for unlimited width. Default: autodetect]:WIDTH: " \
  "(-b= --balloon=)"{-b,--balloon}"[Balloon style to use. Use \"-b list\" to list available styles.]:BALLOON:_ponysay_balloons"

